In [2]:
import torch

x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([2.0], requires_grad=True)

h1 = x * z
h2 = h1**2
y = torch.sin(h2)

y.backward()

print(x.grad)
print(z.grad)
print(h1.grad)

tensor([-5.2291])
tensor([-2.6146])
None


/tmp/ipykernel_1596288/3351244632.py:14: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  print(h1.grad)


In [3]:
h1

tensor([2.], grad_fn=<MulBackward0>)

In [4]:
torch.cos((x*z)**2)*(2*x*z)*z

tensor([-5.2291], grad_fn=<MulBackward0>)